:stylesheet: ../../style.css

= Shadow Api

Java SE and the Java ecosystem offer a multitude of Metaprogramming Apis.
They serve the same purpose just in different contexts.
Annotation processing to analyse classes in the during compilation process, or Reflection to do the same at runtime.
Each having unique concepts and quirks.
This makes Metaprogramming harder to understand and creates a maintenance overhead.
It's very hard to switch from one Api to another.
Once something is written with java.lang.reflect it's hard to change it to an Annotation Processor.
Some JDK Apis are not up to the normal standard.

This project is an Abstraction for Metaprogramming

image::ROOT:Overview.svg[width= 80%]

It has two Types of Apis

== General Purpose Api

This Api works with any kind of Metaprogramming, but the featureset is limited to common operations

.Example
[%collapsible]
====
The Api is request based.
As a caller you can request for example a field of a class.
Accessing fields may or may not be supported.
[%linenums,java]
----
ifndef::site-gen-antora[]
include::../../../src/test/java/io/determann/shadow/article/consistency_test/ApiExampleTest.java[tag=request]
endif::[]
ifdef::site-gen-antora[]
include::Shadow-Api::example$article/consistency_test/ApiExampleTest.java[tag=request]
endif::[]
----

Or use a convenience method if `+Optional.empty()+` or throwing an Exception is a fitting default behavior.

[%linenums,java]
----
ifndef::site-gen-antora[]
include::../../../src/test/java/io/determann/shadow/article/consistency_test/ApiExampleTest.java[tag=requestOrEmpty]
endif::[]
ifdef::site-gen-antora[]
include::Shadow-Api::example$article/consistency_test/ApiExampleTest.java[tag=requestOrEmpty]
endif::[]
----
[%linenums,java]
----
ifndef::site-gen-antora[]
include::../../../src/test/java/io/determann/shadow/article/consistency_test/ApiExampleTest.java[tag=requestOrThrow]
endif::[]
ifdef::site-gen-antora[]
include::Shadow-Api::example$article/consistency_test/ApiExampleTest.java[tag=requestOrThrow]
endif::[]
----
====

== Specific Apis

There is one Api for each kind of Metaprogramming.
One for Annotation processing and another very similar one for reflection.
Each being able to support the complete featureset.

.Example
[%collapsible]
====

.This Annotation Processor generates Builder
[%linenums,java]
----
ifndef::site-gen-antora[]
include::../../../src/test/java/io/determann/shadow/builder/ShadowBuilderProcessor.java[]
endif::[]
ifdef::site-gen-antora[]
include::example$builder/ShadowBuilderProcessor.java[]
endif::[]
----
====

== Supported

- xref:Annotation Processing.adoc[]

- xref:java.lang.model.adoc[]

- xref:Reflection.adoc[] (experimental)

== Next Goals

* Improve Annotation Processing Support
** Add a Java DSL Api for Rendering
** Add support for specific Annotations
* Improve Support for other Metaprogramming Apis
** Move more of the implementation to the `+shadow-implementation-support+`
module for better consistency and easier support of multiple
implementations
** Support the complete Lexical Structure
** Create a maven archetype to reduce the effort of supporting new
Metaprogramming Implementations